"""Add celery task execution scheme

Revision ID: 2e355a8da05b
Revises: d16171e21196
Create Date: 2026-05-17 12:20:11.366725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e355a8da05b'
down_revision: Union[str, Sequence[str], None] = 'd16171e21196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_executions',
    sa.Column('execution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_args_hash', sa.String(length=64), nullable=False),
    sa.Column('celery_task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('ix_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    op.create_index('ix_task_execution_created_at', 'celery_task_executions', ['created_at'], unique=False)
    op.create_index('ix_task_execution_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ix_task_name_args_celery_task_id', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    op.drop_table('collection_1024_50')
    op.drop_index(op.f('collection_1024_100_vector_idx'), table_name='collection_1024_100', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_table('collection_1024_100')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_1024_100',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_1024_100_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_1024_100_pkey'))
    )
    op.create_index(op.f('collection_1024_100_vector_idx'), 'collection_1024_100', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.create_table('collection_1024_50',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_1024_50_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_1024_50_pkey'))
    )
    op.drop_index('ix_task_name_args_celery_task_id', table_name='celery_task_executions')
    op.drop_index('ix_task_execution_status', table_name='celery_task_executions')
    op.drop_index('ix_task_execution_created_at', table_name='celery_task_executions')
    op.drop_index('ix_celery_task_id', table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    # ### end Alembic commands ###
