"""Add celery task execution scheme

Revision ID: 501f8f51fbad
Revises: 2e355a8da05b
Create Date: 2026-05-18 07:04:09.564330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501f8f51fbad'
down_revision: Union[str, Sequence[str], None] = '2e355a8da05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name_args_celery_task_id'), table_name='celery_task_executions')
    op.create_index('ix_task_name_args', 'celery_task_executions', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args', table_name='celery_task_executions')
    op.create_index(op.f('ix_task_name_args_celery_task_id'), 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###
